[package]
authors = ["Andreas Heider <andreas@heider.io>"]
name = "stm32l151"
version = "0.1.0"

[dependencies]
bare-metal = "0.1.1"
cortex-m = "0.3.1"
vcell = "0.1.0"

[dependencies.cortex-m-rt]
optional = true
version = "0.3.6"

[features]
rt = ["cortex-m-rt"]
